query FoodQuery($first: Int, $cursor: Cursor) {
  foods(first: $first, after: $cursor) {
    totalCount
    edges {
      node {
        id
        cuisine
        address
        notes
        rating
        price  
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}